{% set name = "azure-c-shared-utility" %}
{% set version = "2020-12-09" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/Azure/azure-c-shared-utility/archive/{{ version.replace('.', '-') }}.tar.gz
    sha256: 8cf59c75666c4cdffc2f672598668e6ce474c857e1be1ccebeee3edd50cbf69b

build:
  number: 0
  skip: true  # [not win64]
  run_exports:
    - {{ pin_subpackage(name, exact=True) }}

requirements:
  build:
    - vs2017_win-64          # [win64]
    - cmake
    - ninja
  host:
    - azure-macro-utils-c
    - umock-c
  run:
    - azure-macro-utils-c
    - umock-c

test:
  commands:
    - if not exist %PREFIX%\\Library\\bin\\aziotsharedutil.dll exit 1  # [win]

about:
  home: https://github.com/Azure/azure-c-shared-utility
  license: MIT
  license_file: LICENSE
  summary: |
    Azure C Shared Utility

extra:
  recipe-maintainers:
    - seanyen
