{% set name = "azure-c-shared-utility" %}
{% set version = "2020.12.09" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/Azure/azure-c-shared-utility/archive/{{ version.replace('.', '-') }}.tar.gz
    sha256: 8cf59c75666c4cdffc2f672598668e6ce474c857e1be1ccebeee3edd50cbf69b

build:
  number: 2
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}  # [linux]
    - cmake
    - make   # [not win]
    - ninja  # [win]
    - pkg-config  # [unix]
  host:
    # 2022.08.09 is the first backward-incompatible version after
    # azure-macro-utils-c was renamed to macro-utils-c.
    # See: https://github.com/conda-forge/azure-macro-utils-c-feedstock/commit/abca76cfa9b6738d76e44fb5428559d4f245808c
    - azure-macro-utils-c <2020.10.29
    - libuuid  # [unix]
    - umock-c
    - libcurl
    - curl
  run:
    - azure-macro-utils-c <2020.10.29
    - umock-c

test:
  commands:
    - if not exist %PREFIX%\\Library\\bin\\aziotsharedutil.dll exit 1  # [win]
    - test -f "${PREFIX}/lib/libaziotsharedutil${SHLIB_EXT}"  # [not win]

about:
  home: https://github.com/Azure/azure-c-shared-utility
  license: MIT
  license_file: LICENSE
  summary: |
    Azure C Shared Utility

extra:
  recipe-maintainers:
    - jdblischak
    - jjerphan
    - seanyen
    - xylar
